package sqlite3

// Code generated by dbtpl. DO NOT EDIT.

import (
	"database/sql"
)

// CREATE VIEW a_view_of_everything_some AS   SELECT a_bool, a_text FROM a_bit_of_everything
type AViewOfEverythingSome struct {
	ABool sql.NullBool   `json:"a_bool"` // a_bool
	AText sql.NullString `json:"a_text"` // a_text
}
