package sqlserver

// Code generated by dbtpl. DO NOT EDIT.

// CREATE VIEW a_view_of_everything_some AS   SELECT a_bit, a_text FROM a_bit_of_everything;
type AViewOfEverythingSome struct {
	ABit  bool   `json:"a_bit"`  // a_bit
	AText string `json:"a_text"` // a_text
}
