// Code generated by 'yaegi extract github.com/kenshaw/glob'. DO NOT EDIT.

package internal

import (
	"github.com/kenshaw/glob"
	"reflect"
)

func init() {
	Symbols["github.com/kenshaw/glob/glob"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Compile": reflect.ValueOf(glob.Compile),
		"Must":    reflect.ValueOf(glob.Must),
		"New":     reflect.ValueOf(glob.New),
		"Quote":   reflect.ValueOf(glob.Quote),

		// type definitions
		"Glob": reflect.ValueOf((*glob.Glob)(nil)),
	}
}
