package oracle

// Code generated by dbtpl. DO NOT EDIT.

// SELECT a_bool, a_nclob FROM a_bit_of_everything
type AViewOfEverythingSome struct {
	ABool  bool   `json:"a_bool"`  // a_bool
	ANclob string `json:"a_nclob"` // a_nclob
}
