package mysql

// Code generated by dbtpl. DO NOT EDIT.

// select `a_bit_of_everything`.`a_bit_of_everything`.`a_bool` AS `a_bool`,`a_bit_of_everything`.`a_bit_of_everything`.`a_text` AS `a_text` from `a_bit_of_everything`.`a_bit_of_everything`
type AViewOfEverythingSome struct {
	ABool bool   `json:"a_bool"` // a_bool
	AText string `json:"a_text"` // a_text
}
